name: CI - Build e Teste

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Job de Build e Teste
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.1'

      - name: Instalar Yarn
        run: npm install -g yarn

      - name: Yarn install
        run: yarn install

      - name: Execução teste
        run: npm run api
        continue-on-error: true

      - name: Upload relatório JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: test-results/api-junit-results.xml
